# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andrés Arias
tagline:          "Random computer writing"
description:      'A site about hacking embedded systems (and other stuff)'
url:              https://andres.world/
baseurl:          /

author:
  name:           'Andrés Arias'
  url:            https://andres.world/

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/andres-arias/andres-arias.github.io
