# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andrés Arias
tagline:          "Andrés' random computer writing"
description:      'A site about my adventures on DevOps and hacking'
url:              https://andres.world/
baseurl:          /

author:
  name:           'Andrés Arias'
  url:            https://andres-arias.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/andres-arias/andres-arias.github.io
